# Generated by Django 3.2.7 on 2021-09-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('count_from_docs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('words', models.ManyToManyField(through='textCounter.CountTable', to='textCounter.Word')),
            ],
        ),
        migrations.AddField(
            model_name='counttable',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textCounter.document'),
        ),
        migrations.AddField(
            model_name='counttable',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textCounter.word'),
        ),
    ]
