# Generated by Django 3.2.7 on 2021-09-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textCounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='idf',
            field=models.FloatField(default=0),
        ),
    ]
