# Generated by Django 3.2.7 on 2021-09-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textCounter', '0002_word_idf'),
    ]

    operations = [
        migrations.AddField(
            model_name='counttable',
            name='idf',
            field=models.FloatField(default=0),
        ),
    ]
